### ISSUE TITLE
multiple developers

### ISSUE THREAD

**Issue by dwg-andy** [fccotech/ee-db-trace#10]
It does not seem that this will work with a multiple developer environment.  For example, if I have a developer A and a Developer B and a Staging server.  If A commits his db updates to the staging server, B cannot run that same release.  The only way for B to ever get what A has done (or for A to get B's updates), is to do a mysqldump of the Staging Server into A and B's database.  While this isn't horrible and I have it sketched out, how it would work, I'd like to use the built in features of ee-db-trace to push and pull the db between environments.  I tried making everyone the live server with no success or everyone the dev.  
any ideas on making this work? thanks

**Comment by fccotech** [comment]
In case of your situation the idea is that B runs the SQL release that A has created. If B creates an update after that, and the staging needs an update, it would need to run patch A and B in sequence.

Please note that this addon is an concept that needs further improving.

**Comment by dwg-andy** [comment]
thanks, I saw that later that the devs can install other patches.
the concept of this is great.  We spent some time the other day running it through our workflow pretty extensively and found how we could use as long as we know what to watch out for and any shortcomings.
Are you looking for any help on this? I'm a backend dev who has found himself running the front-end team of an EE shop, so I'd love to get involved in something like this if you are looking for contributors.  Do you have any plans on what needs updating or next steps?

**Comment by fccotech** [comment]
Help is very welcome, so please contribute if you can. The main issues that currently are on my "list":

**EE new version compatibility**
When i started developing EE was on version 2.7, so it needs to be updated to support the latest version.

**Driver support**
Adding a MySQLi trace driver

**Query formatting issues**
The trace driver logs queries on very low level. Sometimes queries are formatted in a way that you run into errors, this causes white screens etc. This needs testing, but also the code needs some better regex, exception handling, file permissions checks, etc. Errors are mainly caused by third party addons.

**Store db file next to patch**
Sometimes developers get out of sync (timing issues) in this case i would be nice to have an sql dump with the patch applied. Example case: start version 5, developer A created a patch for v5, I developer B run on version 2, Developer C  created patches for v3&4. So do i need to patch 3&4 from C to get to the base for Developer A and apply the patch of A? If i have an DB dump with the patch, i could directly patch to v5 and see the history developer A has done. (this saves you some syncing form staging servers etc).

**E-mail notifications**
It would be nice to "somehow" get notifications when a new patch is created.could also be done through your VCS (commit hooks etc).

**Comment by dwg-andy** [comment]
awesome.  Looks like a great learning opportunity for me.  thanks
